version: '3'
services:
  jekyll:
    build: .
    ports:
      - 4000:4000
    volumes:
      - ./:/srv/jekyll
    command: bundle exec jekyll serve -d /srv/jekyll/_site --watch --force_polling -H 0.0.0.0 -P 4000
    tty: true